export const AUTH_REQUEST_SEND = "AUTH_REQUEST_SEND"
export const AUTH_SUCCESS: string = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"

export const USER_LOGIN_REQUEST_SEND = "USER_LOGIN_REQUEST_SEND"
export const USER_LOGIN_SUCCESS: string = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const MODELS_FORMAT_OBJ_GET_SUCCESS = "MODELS_FORMAT_OBJ_GET_SUCCESS"

export const MODEL_FORMAT_OBJ_CREATE_REQUEST_SEND = "MODEL_FORMAT_OBJ_CREATE_REQUEST_SEND"
export const MODEL_FORMAT_OBJ_CREATE_SUCCESS = "MODEL_FORMAT_OBJ_CREATE_SUCCESS"
export const MODEL_FORMAT_OBJ_CREATE_ERROR = "MODEL_FORMAT_OBJ_CREATE_ERROR"

export const MODEL_FORMAT_OBJ_DELETE_REQUEST_SEND = "MODEL_FORMAT_OBJ_DELETE_REQUEST_SEND"
export const MODEL_FORMAT_OBJ_DELETE_SUCCESS = "MODEL_FORMAT_OBJ_DELETE_SUCCESS"
export const MODEL_FORMAT_OBJ_DELETE_ERROR = "MODEL_FORMAT_OBJ_DELETE_ERROR"

export const MODELS_REQUEST_SEND = "MODELS_REQUEST_SEND"
export const MODELS_SUCCESS = "MODELS_SUCCESS"
export const MODELS_ERROR = "MODELS_ERROR"
